const express=require('express');
const authController=require('./../controllers/authController');
const userController=require('./../controllers/userController');
const router=express.Router();
router.route('/login').post(authController.login);
router.route('/signup').post(authController.signup);
router.route('/').get(userController.getAllUser);
router.route('/forgot_password').post(authController.forgot_password);
router.route('/reset_password/:id').patch(authController.resetPassword);
router.route('/updatePassword').patch(authController.protect,authController.updatePassword);
router.route('/updateMe').patch(authController.protect,userController.updateMe);
router.route('/deleteMe').patch(authController.protect,userController.deleteMe);
module.exports=router;